version: '3.7'
services:
  database:
    image: postgres:alpine
    restart: unless-stopped
    container_name: sample_db_postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
    ports:
      - "5432"
    volumes:
      # copy sql script to create database
      - ./sql/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - ./enigma:/var/lib/postgresql/data
    networks:
      - sample-go
  
  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    env_file:
      - .env
    networks:
      - sample-go
    ports:
      - "${API_PORT}:${API_PORT}"
volumes:
  enigma:

networks:
  sample-go:
    driver: bridge
