version: '3'
services:
  database:
    image: postgres:latest
    restart: always
    container_name: sample_db_postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - sample-go
  
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - sample-go
    ports:
      - "8081:8081"
volumes:
  data:

networks:
  sample-go:
    driver: bridge